name: leepaulheron
favicon: null
layout_spectrum: 0.5481819978449494
typography_spectrum: 0.7782294033095241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7269675922580063
  lightness: 0.9429733587894589
  saturation: 0.9591230172663927
  rhythmicContrast: 0.29382220888510346
purpose: []
